# Generated by Django 5.0 on 2024-01-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='imageurl',
            field=models.URLField(max_length=5000),
        ),
    ]
